### ISSUE TITLE
Can't access cn models list 

### ISSUE THREAD

**Issue by tonec4d** [coolzilj/Blender-ControlNet#10]
When I go here:
http://localhost:7860/docs#/default/model_list_controlnet_model_list_get

I get an error like this; 
(sorry if this is too newbie)

![image](https://user-images.githubusercontent.com/119037568/223877118-12553402-8242-4567-b589-2512614d114e.png)

**Comment by coolzilj** [comment]
Try update A1111 and controlnet extension to latest, and start A1111 in API mode again.
