### ISSUE TITLE
Feature request: Transferring data- and light passes to multi-controlnet without preprocessors

### ISSUE THREAD

**Issue by MoonMoon82** [coolzilj/Blender-ControlNet#11]
Currently, Blender renders the WHOLE image, passes it to ControlNet with depth-preprocessor to get the (ai-calculated) depthmap of a fully rendered image.

Why not directly passing the different data- and light-passes to controlnet without any preprocessor?

**Comment by MoonMoon82** [comment]
Ok, just saw your "multicn_depth+seg.blend" file. Awesome! But it's just passing the depthmap file. In my case it doesn't seem to calculate the segmentation map. Any suggestions?

**Comment by coolzilj** [comment]
You could bring the depth and segmentation maps to the Web UI directly and see if it works.
In some of my previous cases, I have found that the segmentation map may not be as useful in certain situations.
