### ISSUE TITLE
When Using Character Animations with Depth, Only the First Frame Generates Fully, But Frames Later in the Sequence Do Not

### ISSUE THREAD

**Issue by boricuapab** [coolzilj/Blender-ControlNet#12]
I've noticed that when using an animated 3d character with the depth model only, the first frame in the animation renders the depth map followed by the A1111 render result, but when I go to a frame later in the timeline and activate the script followed by F12 only the depth map gets rendered but not the final result.

![frame0OfAnAnimationRendersAnnot](https://user-images.githubusercontent.com/61924816/224472700-a868df52-4f7d-4ccf-8550-4d6fcfeb1912.png)

![frame207OfAnAnimationDoesNotRenderAnnot](https://user-images.githubusercontent.com/61924816/224472708-90cff22f-da89-4004-8199-d95356ca2712.PNG)

**Comment by coolzilj** [comment]
Yah, known issue.

**Comment by boricuapab** [comment]
I've found a workaround to get it working, though its a bit destructive, just need to slide the keyframes so the keypose I want to render is at frame 0 in the timeline.

![fixedMovingKeyPoseToFrame0](https://user-images.githubusercontent.com/61924816/224516339-abedbca6-89bc-46cc-885e-eecf39666985.PNG)
