### ISSUE TITLE
when run in colab i have this error

### ISSUE THREAD

**Issue by wilzamguerrero** [coolzilj/Blender-ControlNet#13]
Hi. Thanks for this amazing tool, 

[ControlNet] warning: using deprecated 'controlnet_*' request params
[ControlNet] warning: consider using the 'control_units' request param instead
Loading model from cache: control_canny-fp16 [e3fe7712]

**Comment by coolzilj** [comment]
try using the script in https://github.com/coolzilj/Blender-ControlNet/blob/main/blender_templates/multicn_depth%2Bseg.blend

**Comment by enzyme69** [comment]
I am watching this thread, I am also having the same error message. 

And I wonder your blend templates, that one seems to be using Multi ControlNet? Do I also need to use this rig?
https://toyxyz.gumroad.com/l/ciojz?layout=profile

**Comment by coolzilj** [comment]
Migrated to the new ControlNet API already, please refer to the readme for any changes.
