### ISSUE TITLE
Request foe feature enabling Multi ControlNet.

### ISSUE THREAD

**Issue by linilkomban** [coolzilj/Blender-ControlNet#15]
Hi, Thanks for the excellent code.
By using nodes in the Blender compositor we can get multiple images for respective models.
For example:
![MultipleOutput](https://user-images.githubusercontent.com/67116061/224670181-1acad871-582f-4371-b23a-98e861ee92f5.JPG)
In this above setup we get 3 images:
1) the render result which Can be used with any controlNet model (I use it for canny.
![Image0001](https://user-images.githubusercontent.com/67116061/224671209-b411f7e7-3f64-4c28-bda8-d41df10e8444.jpg)

2)the depth map which Can be used with depth controlNet model.
![Image0001](https://user-images.githubusercontent.com/67116061/224671561-dd0d02db-5c2b-4cfe-8620-f9bc5956d010.jpg)

3)the white outline image(I got it using freestyle) which Can be used with depth controlNet model.
![Image0001](https://user-images.githubusercontent.com/67116061/224671997-cbd2aefc-143b-4f87-b061-c5f0407b0f0b.jpg)

Request to please implement feature to use Multiple ControlNet models for better results.

**Comment by coolzilj** [comment]
[Multiple CN is em](https://github.com/coolzilj/Blender-ControlNet/blob/main/blender_templates/multicn_depth%2Bseg.blend)
Checkout this file.
