### ISSUE TITLE
Can't render image if timeline's frame !=0

### ISSUE THREAD

**Issue by kelheor** [coolzilj/Blender-ControlNet#21]
Instead of writing 
`comp_output_depth_filename = "depth0000.png"` 
you need to write something like that: 
`"depth" + f"{bpy.context.scene.frame_current}".zfill(4) + ".png"`
Otherwise, if timeline's frame != 0 (it happened to me, when I set pose for character from animation), then you will get error that depth/seg image not found.

**Comment by coolzilj** [comment]
thx, fixed in 3e6f2c0812893876e3ca7a37a3a082230b1a6c6f
