### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

### ISSUE THREAD

**Issue by Jordain** [coolzilj/Blender-ControlNet#24]
I am trying to run your seg.py and I am running into an error when I try render the scene. This is the error I get RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320). 

I followed your instructions on twitter, not sure if step 2 was important, but it's missing from your twitter instructions posts.

I am still using the older version of controlnet.

**Comment by coolzilj** [comment]
Seems like you were running CN with SD 2.1 model, make sure you're using the compatible version of CN model.

**Comment by Jordain** [comment]
Thanks that was it.
