### ISSUE TITLE
adding multicontrolnet option

### ISSUE THREAD

**Issue by kotaxyz** [coolzilj/Blender-ControlNet#4]
hi there its really awesome script i think it would be better if there is a multicontrolnet option i saw some people made it for houdini it would be awesome if this gets integerated in the script it will help controlling the output more

**Comment by coolzilj** [comment]
https://github.com/Mikubill/sd-webui-controlnet/pull/384
keep an eye on this, once merged, we are ready to rock.

**Comment by ljleb** [comment]
There is an option for this already in the gradio interface. Go to settings > ControlNet > set value of "Multi ControlNet: Max models amount (requires restart)" to something > 1.

**Comment by coolzilj** [comment]
> There is an option for this already in the gradio interface. Go to settings > ControlNet > set value of "Multi ControlNet: Max models amount (requires restart)" to something > 1.

Multi CN API support is not ready, right?

**Comment by ljleb** [comment]
Ah wait this is another repo than /mikubill/controlnet 😂 You need the API to use controlnet.

Yeah, the PR has not been merged yet. I'm waiting to see if anyone finds something that may stop working with the changes.

**Comment by coolzilj** [comment]
> Ah wait this is another repo than /mikubill/controlnet 😂 You need the API to use controlnet.
> 
> Yeah, the PR has not been merged yet. I'm waiting a bit to see if anyone finds something that may stop working with the changes.

Awesome.

**Comment by kotaxyz** [comment]
> [Mikubill/sd-webui-controlnet#384](https://github.com/Mikubill/sd-webui-controlnet/pull/384) keep an eye on this, once merged, we are ready to rock.

let's goooo
