### ISSUE TITLE
Will the Blender Script Be Modified to Work with Multiple Control Nets?

### ISSUE THREAD

**Issue by boricuapab** [coolzilj/Blender-ControlNet#6]
This script is awesome.

Will the script be updated to allow using multiple control nets?

![dreamshaperBlenderResult](https://user-images.githubusercontent.com/61924816/222600068-2b395490-6691-4845-ab34-5118b58c2980.PNG)

**Comment by kotaxyz** [comment]
yes the dev is currently working on it

**Comment by coolzilj** [comment]
add a template https://github.com/coolzilj/Blender-ControlNet/blob/main/blender_templates/multicn_depth%2Bseg.blend
