### ISSUE TITLE
Multi control net Blender issue when using more than one model

### ISSUE THREAD

**Issue by boricuapab** [coolzilj/Blender-ControlNet#9]
When I enable more than one model I am getting this error.

![openPoseNDepth](https://user-images.githubusercontent.com/61924816/223668285-37145c00-993c-413b-8034-b2b7da66c42a.PNG)

**Comment by boricuapab** [comment]
![1678265594-2-after](https://user-images.githubusercontent.com/61924816/223668475-6d953885-472e-48c9-a2b5-35864a48b789.png)

**Comment by coolzilj** [comment]
can you paste your scripts?
